import bcrypt from 'bcrypt';

const data={
  users: [
    {
      name: 'shashini',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'sama',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      _id:'1',
      name: 'Carrot',
      category: 'Shirts',
      image: '/images/d1.png',
      price: 1,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id:'2',
      name: 'Banana',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 3 ,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id:'3',
      name: 'Apple',
      category: 'Shirts',
      image: '/images/d9.jpg',
      price: 2,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
        _id:'4',
      name: 'Nipuna Kiri Samba',
      category: 'Pants',
      image: '/images/d11.png',
      price: 8,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
        _id:'5',
      name: 'Anchor Full Cream Milk Powder',
      category: 'Pants',
      image: '/images/d13.jpeg',
      price: 1,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id:'6',
      name: 'Revello Chocolate',
      category: 'Pants',
      image: '/images/d14.jpeg',
      price: 13,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },

    {
        _id:'7',
      name: 'Kritz Biscuits',
      category: 'Pants',
      image: '/images/d15.jpg',
      price: 5,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
        _id:'8',
      name: 'Cream Cracker',
      category: 'Pants',
      image: '/images/d16.jpeg',
      price: 6,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;