



export default  {
  products:
  [
   {  _id:'1',
      name:'Carrot',
      category:'Slim Shirt',
      image:'/images/d1.png',
      price:200,
      brand:'1Kg',  
      rating:4.5,
      numReviews:10,
      countInStock:0,
    },
    {
      _id:'2',
      name:'Banana',
      category:'Shirts',
      image:'/images/d2.jpg',
      price:60,
      brand:'1kg',
      rating:4.5,
      numReviews:12,
      countInStock:6, 
    },
    {
      _id:'3',
      name:'Cabbage',
      category:'Shirts',
      image:'/images/d18.jpg',
      price:60,
      brand:'1kg',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'4',
      name:'Apple',
      category:'Shirts',
      image:'/images/d9.jpg',
      price:60,
      brand:'1Kg',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },

    {  _id:'5',
      name:'Nipuna Supiri Keeri Samba',
      category:'Shirts',
      image:'/images/d11.png',
      price:60,
      brand:'5kg',  
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'6',
      name:'Anchor Full Cream Milk Powder',
      category:'Shirts',
      image:'/images/d13.jpeg',
      price:60,
      brand:'1kg',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'7',         
      name:'Cocacola Classic', 
      category:'Shirts',
      image:'/images/d19.jpg',
      price:60,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'8',
      name:'Revello Hazelnut', 
      category:'Shirts',
      image:'/images/d14.jpeg',
      price:60,
      brand:'1 L',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },

    {  _id:'9',
      name:'Revello Hazelnut',
      category:'Shirts',
      image:'/images/d16.jpeg',
      price:60,
      brand:'Nike',  
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'10',
      name:'Revello Hazelnut',
      category:'Shirts',
      image:'/images/d22.jpg',
      price:60,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'11',
      name:'Fit Shirt',
      category:'Shirts',
      image:'/images/d14.jpeg',
      price:60,
      brand:'100 g',
      rating:4.5,
      numReviews:10,
      countInStock:6, 
    },
    {
      _id:'12',
      name:'Slims Shirt',
      category:'Shirts',
      image:'/images/d20.jpg',
      price:60,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:8, 
    },
    
  ]
}